### ISSUE TITLE
No target option chosen in recipe

### ISSUE THREAD

**Issue by SchokiCoder** [c2lang/c2c_native#9]
Using a recipe with no "generate-c" or other target option, leaves the user a bit in the dark.
I think adding a warning would be good.

**Comment by bvdberg** [comment]
Good point. This is a historical thing. Eventually this options will go away, since a compiler should generate something by default, unless some options are set (like --check).  Maybe a better name would be 'backend c' (since we also will have a backend llvm / qbe). Let me think about this for a few days..

**Comment by bvdberg** [comment]
changed and pushed to master (only need to update the website documentation, the c2_docs in good). Now the recipe.txt has:
backend c <options>
backend llvm
backend qbe

if no backend is chosen (without --check, -c, -q flags), there will be an error.
